### ISSUE TITLE
Novo Dump 

### ISSUE THREAD

**Issue by Arkanius** [reginaldojunior/winners#47]
Varios erros como:

ALTER TABLE `usuarios`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=24;
[Err] 1833 - Cannot change column 'id': used in a foreign key constraint 'newsletters_ibfk_1' of table 'winners.newsletters'

ALTER TABLE `vendas`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=89;
[Err] 1075 - Incorrect table definition; there can be only one auto column and it must be defined as a key

entre outros

Gerar apenas as tabelas na forma que estão atualmente, sem os alters, vamos ver se assim vai

**Comment by reginaldojunior** [comment]
@Arkanius Como falado, o problema foi resolvido excluindo o database e criando um novo.
