### ISSUE TITLE
Atualizar versão do CakePHP.

### ISSUE THREAD

**Issue by reginaldojunior** [reginaldojunior/winners#48]
Hoje a versão do CakePHP é a 2.x o projeto inteiro deve ser atualizado para a nova versãp 3.x.

**Comment by Arkanius** [comment]
Eita! quer migrar de versão ?

**Comment by reginaldojunior** [comment]
Sim! Estou perdendo muita feature boa do cake 3. Bora migrar junto?

**Comment by Arkanius** [comment]
Bora! Cria um branch ai para a migração!

**Comment by reginaldojunior** [comment]
Criei o branch "cake-version-3.0", a ideia é manter toda a estrutura de controllers e models, e só utilizar o novo core para aproveitar as novas features.

**Comment by reginaldojunior** [comment]
Abandonado, será usado Laravel na nova versão.
