### ISSUE TITLE
Criar automatização para as tabelas

### ISSUE THREAD

**Issue by reginaldojunior** [reginaldojunior/winners#56]
Verificar como automatizar a execução do script sql para assim que o repositório for baixado já rodar todas as tabelas.

**Comment by Arkanius** [comment]
E o migrattion?

**Comment by Arkanius** [comment]
Pode usar os schemas tbm

**Comment by reginaldojunior** [comment]
:+1:  Sim estou pensando nessas alternativas, vou dar uma olhada na documentação de ambas e ver qual melhor se adapta para este caso!

**Comment by reginaldojunior** [comment]
Não será mais feito, a aplicação será rescrita em laravel.

https://github.com/winners-opensource
